### ISSUE TITLE
Deleted issue

### ISSUE THREAD

**Issue by nervousDev** [ammen99/fire#8]

**Comment by ammen99** [comment]
Hi! Which option are you interested in? I will write an implementation of it( sadly this can happen after ~3 days because now I'm on a trip ) but when I get back I'll help you. Just specify which option you want

**Comment by nervousDev** [comment]
You don't need to implement, thank you. Try to explain the best option (for you) of all please with detail. I'm tempted to go with this one:

Have a vec for storing the inserted Pieces and save inside each one the position. Then, when I want to insert a new one, running a collision detection algorithm for all pieces. It might be a bit heavy but I think it's the most straightforward option.

Please let me know what you think. Answer by email and delete this Issue please.

ruifreitas.95@hotmail.com

Thank you,

Rui Freitas.

**Comment by ammen99** [comment]
If you want the solution you quoted:
I suggested making the Piece class/struct as following:
`struct Piece {
    int x, y;
    int w, h;
};`

Then, when
